#pragma once

#include "data_objects.h"

#include <etl/message.h>
#include <etl/vector.h>

#if __cplusplus >= 201703L
    #define __maybe_unused [[maybe_unused]]
#elif defined(__GNUC__) || defined(__clang__)
    #define __maybe_unused __attribute__((__unused__))
#elif defined(_MSC_VER)
    #define __maybe_unused __declspec(unused)
#else
    #define __maybe_unused
#endif


#if defined(__cplusplus) && __cplusplus >= 201703L
    #define __fallthrough [[fallthrough]]
#elif defined(__has_cpp_attribute)
    #if __has_cpp_attribute(fallthrough)
        #define __fallthrough [[fallthrough]]
    #endif
#endif
#ifndef __fallthrough
    #if defined(__GNUC__) || defined(__clang__)
        #define __fallthrough __attribute__((fallthrough))
    #else
        #define __fallthrough
    #endif
#endif

#define BIT(n) (1UL << (n))

namespace pd {

constexpr int MaxExtendedMsgLen = 260;
constexpr int MaxExtendedMsgChunkLen = 26;
constexpr int MaxExtendedMsgLegacyLen = 26;
constexpr int MaxChunksPerMsg = 10;

constexpr int MaxPdoObjects = 11; // 7 for SPR, 11 for EPR.
constexpr int MaxUnchunkedMsgLen = 28;

using PDO_LIST = etl::vector<uint32_t, MaxPdoObjects>;

// Internal top level event bitmasks, for main event loop.
namespace PD_EVENT {
    enum : uint32_t {
        // Generated by timer timeouts or periodic timer
        // (depends on driver implementation)
        TIMER = BIT(0),
        // Dummy flag for hand-generated notifications
        WAKEUP = BIT(1),
        // Event by hardware driver, to detect connector insert/eject
        DRV_UPDATE = BIT(2),
    };
}; // namespace PD_EVENT

class MsgPdEvents : public etl::message<0> {
public:
    explicit MsgPdEvents(uint32_t events) : value{events} {}
    uint32_t value;
    inline bool has_timeout() const { return value & PD_EVENT::TIMER; }
};

class MsgTransitTo : public etl::message<1> {
public:
    explicit MsgTransitTo(int state) : state_id{state} {}
    const int state_id;
};

namespace PD_PACKET_TYPE {
    enum Type {
        SOP = 0,
        SOP_PRIME = 1,
        SOP_PRIME_PRIME = 2,
        SOP_DEBUG_PRIME = 3,
        SOP_DEBUG_PRIME_PRIME = 4,

        INVALID = 0xf
    };
}; // namespace PD_PACKET_TYPE


// 6.3 Control Message
// Table 6.5 Control Message Types
namespace PD_CTRL_MSGT {
    enum Type {
        GoodCRC = 1,
        GotoMin = 2, // Deprecated
        Accept = 3,
        Reject = 4,
        Ping = 5, // Deprecated
        PS_RDY = 6,
        Get_Source_Cap = 7,
        Get_Sink_Cap = 8,
        DR_Swap = 9,
        PR_Swap = 10,
        VCONN_Swap = 11,
        Wait = 12,
        Soft_Reset = 13,
        // rev 3+
        Data_Reset = 14,
        Data_Reset_Complete = 15,
        Not_Supported = 16,
        Get_Source_Cap_Ext = 17,
        Get_Status = 18,
        FR_Swap = 19,
        Get_PPS_Status = 20,
        Get_Country_Codes = 21,
        Get_Sink_Cap_Extended = 22,
        Get_Source_Info = 23,
        Get_Revision = 24,
        // Reserved 25-31
    };
}; // namespace PD_CTRL_MSGT

// 6.4 Data Message
// Table 6.6 Data Message Types
namespace PD_DATA_MSGT {
    enum Type {
        Source_Capabilities = 1,
        Request = 2,
        BIST = 3,
        Sink_Capabilities = 4,
        Battery_Status = 5,
        Alert = 6,
        Get_Country_Info = 7,
        Enter_USB = 8,
        EPR_Request = 9,
        EPR_Mode = 10,
        Source_Info = 11,
        Revision = 12,
        // Reserved 13-14
        Vendor_Defined = 15,
        // Reserved 16-31
    };
}; // namespace PD_DATA_MSGT

// 6.5 Extended Message
// Table 6.53 Extended Message Types
namespace PD_EXT_MSGT {
    enum Type {
        // 0 reserved
        Source_Capabilities_Extended = 1,
        Status = 2,
        Get_Battery_Cap = 3,
        Get_Battery_Status = 4,
        Battery_Capabilities = 5,
        Get_Manufacturer_Info = 6,
        Manufacturer_Info = 7,
        Security_Request = 8,
        Security_Response = 9,
        Firmware_Update_Request = 10,
        Firmware_Update_Response = 11,
        PPS_Status = 12,
        Country_Info = 13,
        Country_Codes = 14,
        Sink_Capabilities_Extended = 15,
        Extended_Control = 16,
        EPR_Source_Capabilities = 17,
        EPR_Sink_Capabilities = 18,
        // Reserved 19-29
        Vendor_Defined_Extended = 30,
        // Reserved 31
    };
};

// 6.2.1.1 Message Header
union PD_HEADER {
    struct {
        uint16_t message_type : 5;
        uint16_t port_data_role : 1; // SOP only, Reserved for SOP'/SOP"
        uint16_t spec_revision : 2;
        uint16_t port_power_role : 1; // SOP only, Cable plug for SOP'/SOP"
        uint16_t message_id : 3;
        uint16_t data_obj_count : 3; // Number of data objects in the message
        uint16_t extended : 1;
    };
    uint16_t raw_value;
};

// 6.2.1.2 Extended Message Header
union PD_EXT_HEADER {
    struct {
        uint16_t data_size : 9;
        uint16_t : 1; // reserved
        uint16_t request_chunk : 1;
        uint16_t chunk_number : 4;
        uint16_t chunked : 1;
    };
    uint16_t raw_value;
};

template <int BufferSize>
struct PD_MSG_TPL {
    PD_HEADER header;
    etl::vector<uint8_t, BufferSize> data;

    inline bool is_data_msg(uint8_t type) {
        return header.extended == 0 && header.data_obj_count > 0 &&
            header.message_type == type;
    }
    inline bool is_ctrl_msg(uint8_t type) {
        return header.extended == 0 && header.data_obj_count == 0 &&
            header.message_type == type;
    }
    inline bool is_ext_msg(uint8_t type) {
        return header.extended > 0 && header.message_type == type;
    }
    inline bool is_ext_ctrl_msg(uint8_t type) {
        if (!is_ext_msg(PD_EXT_MSGT::Extended_Control) || data.size() < 2) {
            return false;
        }
        ECDB ecdb{.raw_value = read16(0)};
        return ecdb.type == type;
    }

    // Helpers to simplify payload access
    inline uint16_t read16(size_t pos) const {
        return uint16_t(data[pos]) | (uint16_t(data[pos + 1]) << 8);
    }
    inline uint32_t read32(size_t pos) const {
        return uint32_t(data[pos]) |
            (uint32_t(data[pos + 1]) << 8) |
            (uint32_t(data[pos + 2]) << 16) |
            (uint32_t(data[pos + 3]) << 24);
    }

    inline void append16(uint16_t value) {
        data.push_back(value & 0xff);
        data.push_back((value >> 8) & 0xff);
    }
    inline void append32(uint32_t value) {
        data.push_back(value & 0xff);
        data.push_back((value >> 8) & 0xff);
        data.push_back((value >> 16) & 0xff);
        data.push_back((value >> 24) & 0xff);
    }
};

using PD_MSG = PD_MSG_TPL<MaxExtendedMsgLen>;

namespace PD_REVISION {
    enum Type {
        REV10 = 0,
        REV20 = 1,
        REV30 = 2
    };
}; // namespace PD_REVISION

} // namespace pd
